---
# set up Mac OS settings via defaults
configure_osx: true

# set up gnupg as ssh-agent
configure_yubikey: true

configure_shell: true

# generate ssh key
configure_ssh: true
ssh_path: ~/.ssh/id_rsa
ssh_size: 4096
ssh_comment: macbook

# configure git config
configure_git: true
git_mail: 51420514+building-from-source@users.noreply.github.com
git_name: building-from-source
git_ignore:
  - "### macOS ###"
  - "# General"
  - .DS_Store
  - .AppleDouble
  - .LSOverride
  - "## Python"
  - ".venv/"
  - "## Core latex/pdflatex auxiliary files:"
  - "*.aux"
  - "*.lof"
  - "*.log"
  - "*.lot"
  - "*.fls"
  - "*.out"
  - "*.toc"
  - "*.fmt"
  - "*.fot"
  - "*.cb"
  - "*.cb2"
  - ".*.lb"

# install stuff via brew
configure_brew: true
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers

homebrew_apps:
  - adobe-creative-cloud
  - discord
  - firefox
  - github
  - mactex-no-gui
  - signal
  - spotify
  - sublime-text
  - synology-drive
  - visual-studio-code
  - yubico-authenticator
  - zoom

homebrew_packages:
  - ansible
  - ansible-lint
  - iperf3
  - nmap
  - pre-commit

# install stuff via app Store
configure_mas: true
mas_apps:
  - { name: 1Password 7 - Password Manager, id: 1295203466 }
  - { name: Apple Configurator 2, id: 1037126344 }
  - { name: Magnet, id: 1333542190 }
  - { name: Microsoft Excel, id: 462058435 }
  - { name: Microsoft Remote Desktop, id: 639968404 }
  - { name: Microsoft Word, id: 462054704 }
  - { name: Parcel - Delivery Tracking, id: 639968404 }
  - { name: WhatsApp Desktop, id: 1147396723 }
  - { name: WireGuard, id: 441258766 }
  - { name: Dictionaries, id: 1380563956 }
